# ---------------- DataSource ----------------
datasource.jdbc-url=jdbc:h2:mem:jdbcdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
datasource.driver-class-name=org.h2.Driver
datasource.username=sa
datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:h2:mem:testdb;NON_KEYWORDS=id;DATABASE_TO_UPPER=FALSE
spring.sql.init.schema-locations=classpath:schema-jdbc.sql
spring.sql.init.data-locations=classpath:data-jdbc.sql
logging.level.org.springframework.web=DEBUG
logging.level.pmo.daw.semi=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always