-- archivo creacion de tablas (reserva se crea por relacion M:M usaurio-destino)

drop table if exists usuario cascade;
drop table if exists destino cascade;
drop table if exists guia cascade;
drop table if exists pasaporte cascade;
drop table if exists reserva cascade;

-- tabla usuario (se comprueba que sea mayor de edad)

create table usuario (
    id integer generated by default as identity,
    nombre varchar(255),
    apellidos varchar(255),
    email varchar(255),
    telefono varchar(255),
    fecha_nacimiento date,
    primary key (id),
    constraint CK_mayor18 check (fecha_nacimiento <= current_date - interval '18 years')
);

-- tabla destino

create table destino (
	id integer generated by default as identity,
	ciudad varchar(255),
	pais varchar(255),
	precio numeric(10,2),
	requiere_pasaporte boolean,
	primary key (id)
);

-- tabla guia (se crea un tipo, para usar enum)

drop type if exists especialidad_guia cascade;
create type especialidad_guia as enum ('Geografia','Historia','Arquitectura','Comida');
create table guia (
	id integer generated by default as identity,
	nombre varchar(255),
	apellidos varchar(255),
	especialidad especialidad_guia,
	primary key (id),
	id_destino integer unique,
	constraint FK_guia_destino foreign key (id_destino) references destino
);

-- tabla pasaporte (se comprueba que el pasaporte no esté caducado a dia de hoy)

create table pasaporte (
    id integer generated by default as identity,
    numero varchar(255),
    pais_expedicion varchar(255),
    fecha_caducidad date,
    primary key (id),
    id_usuario integer unique,
    constraint FK_pasaporte_usuario foreign key (id_usuario) references usuario
    	on delete restrict
    	on update cascade,
    constraint CK_caducidad check (fecha_caducidad > current_date)
);

-- tabla reserva (se añaden campos propios fecha_inicio y fecha_fin)

create table reserva (
	id_usuario integer,
	id_destino integer,
	fecha_inicio date,
	fecha_fin date,
	primary key (id_usuario, id_destino),
	constraint FK_reserva_usuario foreign key (id_usuario) references usuario
		on delete restrict
		on update cascade,
	constraint FK_reserva_destino foreign key (id_destino) references destino
		on delete restrict
		on update cascade
);